"""remove 

Revision ID: 1ace2ef04969
Revises: 0a7911788574
Create Date: 2026-06-12 21:02:45.913151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ace2ef04969'
down_revision: Union[str, Sequence[str], None] = '0a7911788574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('payment_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
