"""create new table and make some changes in previos ones

Revision ID: 52011c32608b
Revises: 9cc5b6add221
Create Date: 2026-06-08 20:49:07.815638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52011c32608b'
down_revision: Union[str, Sequence[str], None] = '9cc5b6add221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.add_column('subscription', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.add_column('subscription', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('subscription', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('subscription', sa.Column('status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'subscription', 'plans', ['plan_id'], ['id'])
    op.drop_column('subscription', 'plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'status')
    op.drop_column('subscription', 'end_date')
    op.drop_column('subscription', 'start_date')
    op.drop_column('subscription', 'plan_id')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
